### ISSUE TITLE
Ability to create a forwarder without the (micro)SD 

### ISSUE THREAD

**Issue by Yrouel** [YANBForwarder/YANBF#10]
It would be nice to be able to specify the path in the microsd without having to physically insert it in the computer to create the forwarder like Forwarder3-DS can do

This would enable creating the cia without ever moving the card from the console and then transfer it either via ftp or even generating a local qrcode

**Comment by lifehackerhansol** [comment]
The reason this is done is because of the collision checking. There is no reliable way to check if the CIA that is about to be created will accidentally replace another app that is installed.

I ended up just requiring the SD, since you have access to the entire title list simply by looking at which folders are there. Then I can check if it's going to accidentally replace another app and get around it.

If you have another suggestion, be my guest, but at least 90 percent of the userbase, I don't think even know what a Title ID is.

**Comment by Yrouel** [comment]
I see. Is that also why the same forwarder (meaning for the same nds) installs twice instead of replacing the existing one?

Anyway I can see it's not a trivial think to fix so well I tried

**Comment by lifehackerhansol** [comment]
> I see. Is that also why the same forwarder (meaning for the same nds) installs twice instead of replacing the existing one?

That is precisely the case. You'll have to delete the old one to install the next one.

I like to think that is just a small inconvenience that just comes from being able to get more than 40 icons. Heck, people are already doing cool things with the banner and sound, so there is clearly an appeal.

If an on-console version ever comes around, hopefully it will ease up the restrictions that the current PC generator has.

I'll leave this open for now in case I think of something else.

**Comment by Yrouel** [comment]
Yeah I moved to YANBF myself exactly because I was bashing my head all day yesterday to make a custom banner for Chrono Trigger because I didn't know bannertool made them for 3DS and it's not compatible with DSiWare.
If would be super cool to have one day the ultimate forwarder creator directly on 3DS to do everything on console

**Comment by Yrouel** [comment]
I found a workaround on Mac by the same principle seems to work on Windows as well:

Basically if you mount the remote ftp or network disk to appear as local drives you can trick the generator into making your cia.

One problem I encountered is that if I didn't specify a local output file it gave me an error because ftp borked itself.
No problem with a locally generated cia which of course needs to be copied over as a separate step.
This to me however seems more a fragility of the ftp server.

On Windows is possible to do pretty much the same but with the built in sd card management and "net use" on the pc

**Comment by lifehackerhansol** [comment]
After I implement the allocated range of UniqueID instead of basing it off the forwarder location (as I explained on GBAtemp), I feel comfortable implementing a "custom ROM location" of sorts.

Stay tuned.

**Comment by lifehackerhansol** [comment]
Current nightly I believe has completely removed the SD card dependency. Passing -p argument will allow you to set a custom ROM path, using the following structure "/path/to/ROM.nds", regardless of what OS YANBF is running on. 

If argument -p is not passed, it will use the path of the input file instead, and if input file is not on the SD card, generation will likely create an incorrect path thus causing the forwarder CIA to fail to boot. 

This should theoretically now have feature parity with Forwarder3-DS (with the same bugs too lol)

Only implemented in CLI for now.

This is not tested. Attempt with caution. I'll test this later today as well.

**Comment by lifehackerhansol** [comment]
Implemented in 1.6.0.
