### ISSUE TITLE
Failed to launch bootstrap.cia on clean install

### ISSUE THREAD

**Issue by bobs50000** [YANBForwarder/YANBF#16]
Hello. So I just got a brand new "New Nintendo 3DS" and followed the guide on 3ds.hacks.guide and installing CFW worked.

I have a cart of Mario 64 DS and I obtained the .nds file from opening the cart in godmode9 and copying it to my sd card.
It is placed in my /roms/nds folder.

I followed the steps on the YANBF github page to install it to my system. I used YANBF v1.5.0 and NTR_Forwarder ver SD-6.

I inserted my SD to my PC, selected the rom from the GUI application, let it generate the .cia in my /cias folder, and then reinsterted my SD to my 3DS and installed that .cia from FBI. All good, shows the game title and an image of the box.

Launch it, and I get a black screen with an error:
"Failed to launch CIA.
Please reinstall bootstrap.cia from YANBF release.
Press START to exit."

I deleted _nds and bootstrap.cia and tried the steps over again, no good.
I tried again with YANBF 1.4.0 and NTR_Forwarder SD-5, no good.
I tried renaming the .nds file and put it in another location, no good.

I don't know what I'm doing wrong. Either the guide is missing a step or something is wrong with bootstrap.cia?

**Comment by lifehackerhansol** [comment]
In FBI's `Titles` section, do you see a `YANBF TWLNAND booter` title?

**Comment by lifehackerhansol** [comment]
Closing due to lack of response.
