### ISSUE TITLE
Forwarder generated with same title ID despite another being already installed

### ISSUE THREAD

**Issue by Yrouel** [YANBForwarder/YANBF#20]
I had the Tetris DS forwarder installed with title ID 0004000000000000 and I created another (for New Super Mario Bros. DS) and it had been assigned the same title ID.
The sd was in my computer, no workarounds.

Using latest version of the generator from command line on Mac

**Comment by Yrouel** [comment]
After being stubborn using 000400000000000000 title id it started working again even with my workaround of mounting the FTP as a local drive and I haven't had a collision since go figure...

If you want to be extra sure to not collide accidentally with existing titles, or at least lower the chance, it'll be ok to generate the json based on installed titles and require to refresh it periodically while also keeping it populated with the generated forwarders.
And in between refreshes it'll work independently.

By the way I was thinking that FBI itself should've at least prompted the user with a warning before replacing an existing title ID but alas that ship has sailed given that it's archived...

**Comment by lifehackerhansol** [comment]
At least the workaround won't be necessary anymore after I clean this up :D

**Comment by lifehackerhansol** [comment]
Fixed (or rather, worked around) in 1.6.0.
