### ISSUE TITLE
Failed to load, please Re-Install Bootstrap.cia 

### ISSUE THREAD

**Issue by Averag3Mang0** [YANBForwarder/YANBF#22]
I got the cias onto my 3ds menu but when I load nothing comes up except that error message, I need help pls. Also I dont have an FBI Titles folder.

**Comment by lifehackerhansol** [comment]
Did you actually install the bootstrap.cia as well?

**Comment by Averag3Mang0** [comment]
with FBI? It never said that in the guide tho?

**Comment by lifehackerhansol** [comment]
Yes it does.
> Boot your 3DS and install both CIAs using FBI

The guide is written with you installing only one forwarder, to begin with. That would mean you have the forwarder icon CIA, as well as the bootstrap.cia file. 

I suppose I can write this out better, but the point is that if you are missing bootstrap.cia the entire forwarder structure fails.

**Comment by lifehackerhansol** [comment]
Actually, on the Graphical User Interface section of the guide, I explicitly say install all CIAs. And a step telling you to copy bootstrap.cia to your SD card was provided in the first section. So you should have installed it anyway.

**Comment by Averag3Mang0** [comment]
I got it fixed! Thank you so much for replying so fast you helped a ton! :)
