### ISSUE TITLE
I wanted to use this new method of forwarding, but I used the old 3ds forwarder and now want to switch

### ISSUE THREAD

**Issue by Averag3Mang0** [YANBForwarder/YANBF#23]
I used to use this old method: https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/
And wanted to use the YANBF method since the older one no longer works. Could I just follow the steps of the new method without having to uninstall other previous files or... cause I don't want to possibly mess up the DS games I already have installed on my 3ds

**Comment by lifehackerhansol** [comment]
Forwarders are just that: shortcuts to your actual ROMs/saves on your SD card.

So as long as you leave that alone, you won't lose your games/saves.

**Comment by lifehackerhansol** [comment]
For future questions like this, please use the discussions tab. Issues are for actual bug reports etc.
