### ISSUE TITLE
bannertool crashes trying to open the banner image

### ISSUE THREAD

**Issue by lifehackerhansol** [YANBForwarder/YANBF#25]
Bannertool is crashing when running `makebanner`, and opening the image to inject into the banner data.

Reproduced by two people thus far.

**Comment by lifehackerhansol** [comment]
@Vent47, I see you were trying to generate SoulSilver forwarder, inside the `data` folder, is there a `boxart.jpg` and a `banner.png` file?

**Comment by Vent47** [comment]
There is a banner.png i put in myself but there's no boxart.jpg

**Comment by Vent47** [comment]
I tried adding the boxart.jpg myself and it made an output.smdh but no CIA and in the GUI it said it failed
[YANBF-poya.log](https://github.com/YANBForwarder/YANBF/files/8682718/YANBF-poya.log)

**Comment by lifehackerhansol** [comment]
So the issue then is that the boxart is not downloading.

I found a few things wrong with the code, perhaps that fixes it. Stay tuned.

**Comment by Trikzon** [comment]
I'd like to add that I seem to have the same issue as I get this log:
```
Mon May 16 2022 23:33:41 GMT-0400 (Eastern Daylight Time): generator.py:63: DeprecationWarning: LINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.

Mon May 16 2022 23:33:51 GMT-0400 (Eastern Daylight Time): generator.py:241: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.

Mon May 16 2022 23:33:52 GMT-0400 (Eastern Daylight Time): Custom path is not provided. Using path for input file.
/roms/nds/The Legend of Zelda - Spirit Tracks.nds
Getting gamecode...
Extracting and resizing icon...
Getting ROM titles...
Creating SMDH...
Checking API if a custom banner or sound is provided...
No banner provided. Checking GameTDB for standard boxart...
Resizing banner...
Creating banner...
ERROR: Could not load image file: can't fopen.
```

It correctly has a `banner.png`, `boxart.jpg`, and `icon.png` in the data folder

The same error occurs when running the generator through the terminal instead of the gui.

However, this error is only happening for me on and M1 Macbook running macOS Monterey. I tried the same thing on my Windows 10 machine and it created a working .cia file for my ROM.

**Comment by lifehackerhansol** [comment]
I think I found part of the issue.

A new nightly will be up soon.

**Comment by lifehackerhansol** [comment]
There appears to be quite a bit of permissions issues on macOS Monterey. macOS has made some internal changes that make it rather difficult to do anything via the command-line tools. I'm not sure how to get around that, though. I still refuse to upgrade my Mac to Monterey just for this.

@Vent47's log, while very appreciated, makes things even more confusing. The log seems to be incomplete for some reason? I've had a shit ton of issues with that last release... perhaps I should implement some form of verbose logging.

**Comment by Vent47** [comment]
Just tried with the nightly and this is what the console said

![image](https://user-images.githubusercontent.com/92400243/168843343-5fdb6ec8-c1f9-4b34-b9ef-f02a95e8b009.png)

**Comment by Vent47** [comment]
I tried again with the new nightly and same thing happened. I've been using the windows version, should I use the regular version?

![image](https://user-images.githubusercontent.com/92400243/168895858-bfc89281-5e0b-448e-859d-aa6fee3d3c92.png)

**Comment by lifehackerhansol** [comment]
*Now* I'm lost.

Is there a space in your username? Or any special characters?

**Comment by Vent47** [comment]
Yeah my username has an é. Is that what breaks everything?

**Comment by lifehackerhansol** [comment]
Entirely possible...

Can you try moving the whole generator folder to C:\?

**Comment by lifehackerhansol** [comment]
So at this point, I've fixed what's left of _YANBF_ code.

It's possible that now we're reaching issues outside of my control, i.e. bannertool which is used in this project (and many others.) bannertool has a history of breaking with Unicode paths, which is where I'm deducing is the problem.

I've contacted the maintainer of the version of bannertool I'm using and they're looking into it. If running `generator` in C:\ as opposed to in your user directory works, then I think there is not much I can do.

**Comment by Epicpkmn11** [comment]
This should be fixed by my bannertool fork [v1.2.2](https://github.com/Epicpkmn11/bannertool/releases/tag/v1.2.2), the specific error here was (assuming your Windows is using a locale with accent e) a regression in my v1.2.1 that broke non-ASCII file names in the current code page, but I've fixed that and done it better so now *any* file name should work, even Japanese and Korean names and the same time or something like that that isn't possible without Unicode.

**Comment by Vent47** [comment]
Ok it works if the generator folder is in C:\

**Comment by Vent47** [comment]
It works now from the desktop so yeah I think it's fixed

**Comment by lifehackerhansol** [comment]
I will mark it as closed, then. Thank you for all the testing!
