### ISSUE TITLE
Some games not being processed through the generator

### ISSUE THREAD

**Issue by thebestcoderofcourse** [YANBForwarder/YANBF#26]
Hello Yanbf Team,

I hope you are well. I am just installing your software. It works amazingly. I have a couple of questions when you have a moment.

For some reason, there are a couple of games that aren't going through the yanbf generator. Mainly Heartgold, New super mario bros.

It seems that I get this error: ValueError: write to a closed file

Is there any way I should proceed? Thank you for your time.

**Comment by lifehackerhansol** [comment]
This is a bug. I'll fix it.

**Comment by thebestcoderofcourse** [comment]
Thank you so much for helping with this. I really appreciate it. I found a couple more bugs (which are consistent in both applications and command prompt. Would it be ok if I list them below? 11/12 of them are the same.

Phantom Hourglass: ValueError: write to closed file
Tetris DS: ValueError: write to closed file
Animal Crossing Wild World: ValueError: write to closed file
CronoTrigger: ValueError: write to closed file
Contra 4: ValueError: write to closed file
New Super Mario Bros: ValueError: write to closed file
Pokemon Black: ValueError: write to closed file
Pokemon Soul Silver: ValueError: write to closed file
Mario Kart DS: ValueError: write to closed file
Pokemon Heartgold: ValueError: write to closed file
Pokemon White: ValueError: write to closed file

Bakugan Battle Brawlers: Banner was not found. Exiting. (I assume If I add this file it would work)


Thank you again for helping me with this. I really do appreciate this yanbf.

**Comment by lifehackerhansol** [comment]
I can't find an instance where it would break like this, but I just pushed some workaround code. A nightly build will be up in about 10 minutes.

**Comment by thebestcoderofcourse** [comment]
Honestly thank you so much. I really appreciate you helping me with this.

**Comment by lifehackerhansol** [comment]
Please test the nightly build here: https://nightly.link/YANBForwarder/YANBF/workflows/nightly/main

Only CLI builds are provieded in nightlies. But it's possible to use the older GUI on it, if you want.

**Comment by thebestcoderofcourse** [comment]
Thank you so much for your help. I seem to have gotten a different error:
ERROR: Failed to open file for CWAV conversion: Permission denied

Any thoughts? I really appreciate you helping

**Comment by thebestcoderofcourse** [comment]
Hello. Life Hackerhansol.

After checking it again it seems to work perfectly! Thank you so much for your help. I really appreciate it.
