### ISSUE TITLE
Linux 1.6.3 conversion does not start

### ISSUE THREAD

**Issue by Amnesia1000** [YANBForwarder/YANBF#45]
When I run appimage, add the games, set up the folders, and when I click on the download icon, it keeps spinning the icon but does not advance.
![Captura desde 2022-12-22 12-14-55](https://user-images.githubusercontent.com/45115804/209164990-19d68639-f58d-4f4b-833f-fa60e37fa1d4.png)

In addition, no files are created in the logs folder.

**Comment by lifehackerhansol** [comment]
Try setting the `Generator directory` to the folder where the Appimage is.

**Comment by Amnesia1000** [comment]
Thats works. Thanks
