### ISSUE TITLE
CIA's not forming properly

### ISSUE THREAD

**Issue by eddyvs** [YANBForwarder/YANBF#63]
When i follow all the instuctions and set my rom path as well as my generator paths to the according files, the generated CIA's are extremely small and do not load anything when installed on FBI. Am i missing somthing? 

for comparison, the original game is about ~65 mb and after it becomes 500 kb.
![Screenshot (44)](https://github.com/YANBForwarder/YANBF/assets/139392157/3ab85816-9d69-4960-b84c-3d293f55d64f)
![Screenshot (45)](https://github.com/YANBForwarder/YANBF/assets/139392157/0e086ce4-1ed5-446a-b4b0-5e4ed19e9f84)

Thanks!

**Comment by lifehackerhansol** [comment]
Forwarders are shortcut icons; they do nothing other than pass to nds-bootstrap the location of your real ROM on the SD card. They do not contain the actual ROM in question.

**Comment by eddyvs** [comment]
> Forwarders are shortcut icons; they do nothing other than pass to nds-bootstrap the location of your real ROM on the SD card. They do not contain the actual ROM in question.

Thanks! I realized that quickly after I made the post. It works great by the way it’s a really awesome tool!
