### ISSUE TITLE
Start Failed. Error -1

### ISSUE THREAD

**Issue by Baochaotao** [YANBForwarder/YANBF#65]
Good afternoon, 
I appreciate all the work put into this!
I made a new account to post this issue:

I followed all the prior steps to installation.
I attempted to execute the final steps without removing my SD card, and instead used the built-in Data transfer functionally. 

When making my custom ROM path in the GUI, I specified the Folders my DS rom is in, ex: "/roms/nds"
When I download the curated .cia file, everything looks fine.
I boot the game, from the home screen and im greeted by a long wait time, and a black screen. 
Eventually the screen flashes, then gives me an error code on the bottom screen.

Start Failed. Error -1

I'd appreciate some help with this, I've been avoiding doing this process without removing my SD card.

Edit: 
Fixed!
Just needed to specify the ROM path further.
Edited the .text file in the Forwarder File additionally to match. 
Deleted prior installed CIA.'s from the GUI on the 3ds,, and started fresh.

Thanks All!

**Comment by Pitahayaro** [comment]
Hi, could you tell me how you exactly resolved your issue, please? My path is also /roms/nds, and I'm experiencing the same error. I've been trying various solutions without success and can't seem to find a solution.
